dict: /home/changhengyi/rnnt-decode_test/dict.txt
cmvn_path: /home/changhengyi/rnnt-decode_test/cmvn.ark
wp_model: ""

### data
num_workers: 2
min_n_frames: 0
max_n_frames: 1600
vocab: 1505
mode: "char"

### encoder
subsample_factor: 4
enc_layers: 5
enc_input_dim: 640
enc_num_units: 512
### decoder
dec_layers: 2
dec_num_units: 1024
emb_dim: 512
joint_dim: 512
### loss
clip_grad_norm: 5.0
ctc_weight: 0.3
rnnt_weight: 0.7
param_init: 0.1
ctc_lsm_prob: 0.1
ctc_fc_list: "512"
dropout_dec: 0.4
dropout_emb: 0.4

### optimization
batch_size: 15
optimizer: adam
n_epochs: 30
print_step: 1000
sort_stop_epoch: 100
lr: 1e-3
weight_decay: 1e-6
lr_decay_start_epoch: 20
lr_decay_rate: 0.85
dynamic_batching: True
shuffle_bucket: False


